Vagrant.configure("2") do |config|

  config.vm.define "rchelseaS" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "rchelseaS"
    server.vm.network "private_network", ip: "192.168.56.110", auto_config: true # Устанавливаем статический IP
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "2048" # Устанавливаем объем памяти
      vb.cpus = 2 # Устанавливаем количество процессоров
#     server.vm.network "forwarded_port", guest: 80, host: 80
    end

    # Настраиваем SSH-доступ без пароля
    server.vm.provision "shell", inline: <<-SHELL

      sudo apt-get update
      sudo apt-get install -y curl openssh-server
      sudo systemctl enable ssh
      sudo systemctl start ssh
      curl -sfL https://get.k3s.io | sh -
      export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
      sudo chmod 644 /etc/rancher/k3s/k3s.yaml

      while [ ! -f /vagrant/confs/manifest.yaml ]; do
        echo "Waiting for manifest.yaml to be available..."
        sleep 10
      done

      kubectl apply -f /vagrant/confs/manifest.yaml
      SHELL

    end
  end

