Vagrant.configure("2") do |config|

  # Configure VM
  config.vm.define "rchelseaS" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "rchelseaS"
    server.vm.network "private_network", ip: "192.168.56.110", auto_config: true
    server.vm.synced_folder "./static", "/shared/static"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end
    
    server.vm.provision "shell", path: "scripts/init_server.sh"
    
  end

end
