Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20240905.1"
  config.vm.boot_timeout = 600

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
    vb.linked_clone = true
  end

  config.vm.define "okushnirS" do |server|
    server.vm.hostname = "okushnirS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "okushnirS"
    end
    server.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install -y curl
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip 192.168.56.110" K3S_KUBECONFIG_MODE="644" sh -
    cp /var/lib/rancher/k3s/server/node-token /vagrant/ 
    SHELL
  end
  
  config.vm.define "okushnirSW" do |worker|
    worker.vm.hostname = "okushnirSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", inline: <<-SHELL
    while [ ! -f /vagrant/node-token ]; do
      sleep 2
    done
    sudo apt-get update -y
    sudo apt-get install -y curl
    curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip 192.168.56.111" K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$(cat /vagrant/node-token) sh -      
    rm /vagrant/node-token
    SHELL
  end
end
