Vagrant.configure("2") do |config|

  config.vm.define "rchelseaS" do |server|
    server.vm.box = "debian/bookworm64"
    server.vm.hostname = "rchelseaS"
    server.vm.network "private_network", ip: "192.168.56.110", auto_config: true # Устанавливаем статический IP
    server.vm.synced_folder ".", "/shared"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "7044" # Устанавливаем объем памяти
      vb.cpus = 6 # Устанавливаем количество процессоров
    end
    
    config.vm.network "forwarded_port", guest: 8080, host: 8081  #argocd jjacquel
    # config.vm.network "forwarded_port", guest: 8888, host: 1234  #app jjacquel
    config.vm.network "forwarded_port", guest: 80, host: 8085 # gitlab rchelsea
    config.vm.network "forwarded_port", guest: 8082, host: 1234 #app bonus
    config.vm.network "forwarded_port", guest: 8090, host: 8091 #app_bonus_rchelsea
    

    # Настраиваем SSH-доступ без пароля
    server.vm.provision "shell", inline: <<-SHELL

      sudo apt-get update
      sudo apt-get install -y curl openssh-server
      sudo systemctl enable ssh
      sudo systemctl start ssh
      
      SHELL

    end
  end

